spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/forum?serveTime=UTC&useUnicode=true&characterEncoding=utf-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


#Jwt properties
macro:
    app:
      jwtSecret: macrosSecret
      jwtExpirationMs: 86400000   #24h